DOMAIN: 'https://domain.tld'
SECRET: 'very long secret, e.g. os.urandom(24)'
# for a good cryptographic secret key do the following:
# >>> import os
# >>> os.urandom(24)
# '\xfd{H\xe5<\x95\xf9\xe3\x96.5\xd1\x01O<!\xd5\xa2\xa0\x9fR"\xa1\xa8'

NETWORKS:
  - DISCORD
  - IRC
  - MATRIX

DISCORD:
  API_ENDPOINT: 'https://discordapp.com/api/v6'
  CLIENT_ID: '123456789012345678'
  CLIENT_SECRET: '1234567890abcdefghijklmnopqrstuv'              
  BOT_TOKEN: '1234567890abcdefghijklmnopqrstuvxyz-._1234567890abcdefghijk'
  CDN_URI: 'https://cdn.discordapp.com'
